services:
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    image: todo-frontend-prod
    container_name: todo-frontend

  nginx:
    image: todo-frontend-prod #nginx:1.25-alpine
    container_name: reverse-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
